In [76]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/customer-1/customer1_dataset.csv


In [77]:
data =pd.read_csv("/kaggle/input/customer-1/customer1_dataset.csv",parse_dates=['purchase_date'])


In [78]:
# Convert 'purchase_date' to datetime format
data["purchase_date"] = pd.to_datetime(data["purchase_date"])

# Extract the relevant date parts
data["saleYear"] = data["purchase_date"].dt.year
data["saleMonth"] = data["purchase_date"].dt.month
data["saleDay"] = data["purchase_date"].dt.day
data["saleDayofWeek"] = data["purchase_date"].dt.dayofweek
data["saleDayofYear"] = data["purchase_date"].dt.dayofyear
data.sort_values(by=['purchase_date'],inplace=True,ascending=True)
# Drop the 'purchase_date' column as it's no longer needed
data = data.drop('purchase_date', axis=1)


In [79]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 8937 to 6984
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   customer_id           10000 non-null  object 
 1   session_id            10000 non-null  int64  
 2   interaction_type      10000 non-null  object 
 3   product_id            10000 non-null  object 
 4   category              10000 non-null  object 
 5   location              7877 non-null   object 
 6   browsing_history      10000 non-null  object 
 7   cart_items            10000 non-null  object 
 8   saved_for_later       10000 non-null  object 
 9   purchase_status       10000 non-null  object 
 10  discounted            10000 non-null  bool   
 11  feedback_rating       7075 non-null   float64
 12  preferred_categories  10000 non-null  object 
 13  saleYear              10000 non-null  int32  
 14  saleMonth             10000 non-null  int32  
 15  saleDay               

In [80]:
data.isna().sum()

customer_id                0
session_id                 0
interaction_type           0
product_id                 0
category                   0
location                2123
browsing_history           0
cart_items                 0
saved_for_later            0
purchase_status            0
discounted                 0
feedback_rating         2925
preferred_categories       0
saleYear                   0
saleMonth                  0
saleDay                    0
saleDayofWeek              0
saleDayofYear              0
dtype: int64

In [81]:
data["location"]=data["location"].fillna("unrecorded")

In [82]:
data["feedback_rating"]=data["feedback_rating"].fillna(int(np.random.randint(5)))

In [83]:
data

customer_id  session_id interaction_type product_id     category  \
8937   customer1          68          offline      P0143   Home Decor   
697    customer1          42          offline      P0056     Clothing   
2332   customer1          49          offline      P0393        Books   
2696   customer1          70           online      P0362   Home Decor   
1713   customer1          28          offline      P0370     Clothing   
...          ...         ...              ...        ...          ...   
7093   customer1          26          offline      P0151     Clothing   
3181   customer1          63          offline      P0477   Home Decor   
4350   customer1          60           online      P0329   Home Decor   
4787   customer1          36          offline      P0343  Electronics   
6984   customer1          27          offline      P0019   Home Decor   

           location                                   browsing_history  \
8937        Chicago                       ['Electronics', 'Groceries']   
697        New York                                      ['Groceries']   
2332     unrecorded             ['Books', 'Home Decor', 'Electronics']   
2696       New York                                     ['Home Decor']   
1713     unrecorded     ['Books', 'Books', 'Groceries', 'Electronics']   
...             ...                                                ...   
7093       New York  ['Clothing', 'Electronics', 'Clothing', 'Cloth...   
3181        Chicago          ['Books', 'Home Decor', 'Books', 'Books']   
4350    Los Angeles                     ['Electronics', 'Electronics']   
4787  San Francisco                              ['Books', 'Clothing']   
6984    Los Angeles           ['Groceries', 'Groceries', 'Home Decor']   

                       cart_items     saved_for_later purchase_status  \
8937           ['P0436', 'P0357']           ['P0206']       Purchased   
697            ['P0182', 'P0034']                  []       Purchased   
2332           ['P0131', 'P0308']           ['P0067']       Purchased   
2696                    ['P0198']           ['P0088']       Purchased   
1713  ['P0298', 'P0395', 'P0429']                  []       Purchased   
...                           ...                 ...             ...   
7093                    ['P0405']                  []       Purchased   
3181  ['P0218', 'P0420', 'P0451']                  []   Not Purchased   
4350  ['P0200', 'P0352', 'P0009']                  []   Not Purchased   
4787  ['P0059', 'P0153', 'P0442']  ['P0247', 'P0452']       Purchased   
6984  ['P0056', 'P0260', 'P0407']  ['P0425', 'P0066']       Purchased   

      discounted  feedback_rating preferred_categories  saleYear  saleMonth  \
8937       False              5.0             Clothing      2024          1   
697        False              4.0          Electronics      2024          1   
2332       False              0.0             Clothing      2024          1   
2696       False              0.0                Books      2024          1   
1713       False              5.0                Books      2024          1   
...          ...              ...                  ...       ...        ...   
7093       False              4.0            Groceries      2024         12   
3181        True              0.0                Books      2024         12   
4350        True              4.0          Electronics      2024         12   
4787       False              5.0             Clothing      2024         12   
6984       False              3.0             Clothing      2024         12   

      saleDay  saleDayofWeek  saleDayofYear  
8937        1              0              1  
697         1              0              1  
2332        1              0              1  
2696        1              0              1  
1713        1              0              1  
...       ...            ...            ...  
7093       30              0            365  
3181       30              0            365  

In [84]:
for label,content in data.items():
    if pd.api.types.is_object_dtype(content):
        print(label)

customer_id
interaction_type
product_id
category
location
browsing_history
cart_items
saved_for_later
purchase_status
preferred_categories


In [85]:
for label,content in data.items():
    if pd.api.types.is_object_dtype(content):
        data[label]=content.astype('category').cat.as_ordered()

In [86]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 8937 to 6984
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype   
---  ------                --------------  -----   
 0   customer_id           10000 non-null  category
 1   session_id            10000 non-null  int64   
 2   interaction_type      10000 non-null  category
 3   product_id            10000 non-null  category
 4   category              10000 non-null  category
 5   location              10000 non-null  category
 6   browsing_history      10000 non-null  category
 7   cart_items            10000 non-null  category
 8   saved_for_later       10000 non-null  category
 9   purchase_status       10000 non-null  category
 10  discounted            10000 non-null  bool    
 11  feedback_rating       10000 non-null  float64 
 12  preferred_categories  10000 non-null  category
 13  saleYear              10000 non-null  int32   
 14  saleMonth             10000 non-null  int32   
 15  saleD

In [87]:
data["location"].cat.codes

8937    0
697     2
2332    4
2696    2
1713    4
       ..
7093    2
3181    0
4350    1
4787    3
6984    1
Length: 10000, dtype: int8

In [88]:

for label,content in data.items():
    if not pd.api.types.is_numeric_dtype(content):
        # Turn categories into number , and add one
        data[label] = pd.Categorical(content).codes + 1

In [89]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 8937 to 6984
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   customer_id           10000 non-null  int8   
 1   session_id            10000 non-null  int64  
 2   interaction_type      10000 non-null  int8   
 3   product_id            10000 non-null  int16  
 4   category              10000 non-null  int8   
 5   location              10000 non-null  int8   
 6   browsing_history      10000 non-null  int16  
 7   cart_items            10000 non-null  int16  
 8   saved_for_later       10000 non-null  int16  
 9   purchase_status       10000 non-null  int8   
 10  discounted            10000 non-null  bool   
 11  feedback_rating       10000 non-null  float64
 12  preferred_categories  10000 non-null  int8   
 13  saleYear              10000 non-null  int32  
 14  saleMonth             10000 non-null  int32  
 15  saleDay               

In [90]:
data.isna().sum()

customer_id             0
session_id              0
interaction_type        0
product_id              0
category                0
location                0
browsing_history        0
cart_items              0
saved_for_later         0
purchase_status         0
discounted              0
feedback_rating         0
preferred_categories    0
saleYear                0
saleMonth               0
saleDay                 0
saleDayofWeek           0
saleDayofYear           0
dtype: int64

In [91]:
from sklearn.ensemble import RandomForestRegressor 
model = RandomForestRegressor(n_jobs=-1 , random_state = 42)

In [92]:
X = data.drop("preferred_categories",axis = 1)
y = data["preferred_categories"]

In [93]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train , y_test = train_test_split(X,y)

In [94]:
model.fit(X_train , y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [95]:
y_preds = model.predict(X_test)
y_test.info()

<class 'pandas.core.series.Series'>
Index: 2500 entries, 1362 to 7040
Series name: preferred_categories
Non-Null Count  Dtype
--------------  -----
2500 non-null   int8 
dtypes: int8(1)
memory usage: 22.0 KB


In [96]:
model.score(X_test , y_test)

-0.02910527752597636

In [97]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize the model
model = RandomForestClassifier(n_jobs=-1, random_state=42)

# Fit the model
model.fit(X_train, y_train)

# Make predictions
y_preds = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_preds)
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(classification_report(y_test, y_preds))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_preds))


Accuracy: 0.2092
Classification Report:
              precision    recall  f1-score   support

           1       0.20      0.23      0.21       503
           2       0.20      0.20      0.20       480
           3       0.21      0.21      0.21       507
           4       0.22      0.23      0.23       498
           5       0.21      0.17      0.19       512

    accuracy                           0.21      2500
   macro avg       0.21      0.21      0.21      2500
weighted avg       0.21      0.21      0.21      2500

Confusion Matrix:
[[114  99 102 104  84]
 [101  98 107  83  91]
 [118  99 109 107  74]
 [122  94  96 115  71]
 [107 109  99 110  87]]


In [98]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

# Load the dataset
data = pd.read_csv("/kaggle/input/customer-1/customer1_dataset.csv", parse_dates=['purchase_date'])

# Preprocessing: Feature Engineering
data["purchase_date"] = pd.to_datetime(data["purchase_date"])
data["saleYear"] = data["purchase_date"].dt.year
data["saleMonth"] = data["purchase_date"].dt.month
data["saleDay"] = data["purchase_date"].dt.day
data["saleDayofWeek"] = data["purchase_date"].dt.dayofweek
data["saleDayofYear"] = data["purchase_date"].dt.dayofyear
data.sort_values(by=['purchase_date'], inplace=True, ascending=True)
data = data.drop('purchase_date', axis=1)

# Handling missing values
data["location"] = data["location"].fillna("unrecorded")
data["feedback_rating"] = data["feedback_rating"].fillna(int(np.random.randint(5)))

# Splitting the dataset into features and target
X = data.drop("preferred_categories", axis=1)
y = data["preferred_categories"]

# Preprocessing: Column Transformer
categorical_features = X.select_dtypes(include=['object']).columns
numeric_features = X.select_dtypes(include=['int64', 'int32', 'float64']).columns

# Define the preprocessing for categorical data
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

# Define the preprocessing for numerical data
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

# Combine preprocessing steps
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Define the model pipeline
model_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_jobs=-1, random_state=42))
])

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Define hyperparameter grid for GridSearchCV
param_grid = {
    'classifier__n_estimators': [100, 200, 300],
    'classifier__max_depth': [None, 10, 20, 30],
    'classifier__min_samples_split': [2, 5, 10],
    'classifier__min_samples_leaf': [1, 2, 4],
}

# GridSearchCV
grid_search = GridSearchCV(model_pipeline, param_grid, cv=3, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

# Best parameters
print("Best parameters found: ", grid_search.best_params_)

# Predict with the best model
best_model = grid_search.best_estimator_
y_preds = best_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_preds)
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(classification_report(y_test, y_preds))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_preds))


Fitting 3 folds for each of 108 candidates, totalling 324 fits
[CV] END classifier__max_depth=None, classifier__min_samples_leaf=1, classifier__min_samples_split=2, classifier__n_estimators=200; total time=  22.1s
[CV] END classifier__max_depth=None, classifier__min_samples_leaf=1, classifier__min_samples_split=2, classifier__n_estimators=300; total time=  35.0s
[CV] END classifier__max_depth=None, classifier__min_samples_leaf=1, classifier__min_samples_split=5, classifier__n_estimators=200; total time=  14.7s
[CV] END classifier__max_depth=None, classifier__min_samples_leaf=1, classifier__min_samples_split=10, classifier__n_estimators=100; total time=   6.7s
[CV] END classifier__max_depth=None, classifier__min_samples_leaf=1, classifier__min_samples_split=10, classifier__n_estimators=100; total time=   6.9s
[CV] END classifier__max_depth=None, classifier__min_samples_leaf=1, classifier__min_samples_split=10, classifier__n_estimators=100; total time=   6.6s
[CV] END classifier__max_dep